name: Release Builds

on:
  release:
    ignore-forks: true
    types: [published]

jobs:
  build:
    if: "github.repository == 'gantry/gantry5' && !github.event.release.prerelease"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          extensions: opcache, gd
          tools: composer:v2
          coverage: none
        env:
          COMPOSER_TOKEN: ${{ secrets.GLOBAL_TOKEN }}
      - name: Install packages
        run: |
          sudo apt-get -y update -qq  < /dev/null > /dev/null
          sudo apt-get -y install -qq git zip < /dev/null > /dev/null
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir -d bin/builder)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Build Gantry packages (using CHANGELOG.md to get the version)
        run: composer build-prod

      # TODO: Release should also trigger a build, but with PROD
      # TODO: Release should also trigger updating of master with prod-versions update
      # TODO: develop should push to S3 bucket
#      - name: Upload Gantry Release
#        id: upload-release
#        uses: alexellis/upload-assets@0.2.3
#        env:
#          GITHUB_TOKEN: ${{ secrets.GLOBAL_TOKEN }}
#        with:
#          asset_paths: '["./dist/*.zip"]'

#  slack:
#    name: Slack
#    needs: build
#    runs-on: ubuntu-latest
#    if: always()
#    steps:
#      - uses: technote-space/workflow-conclusion-action@v2
#      - uses: 8398a7/action-slack@v3
#        with:
#          status: failure
#          fields: repo,message,author,action
#          icon_emoji: ':octocat:'
#          author_name: 'Github Action Build'
#          text: '🚚 Automated Build Failure'
#        env:
#          GITHUB_TOKEN: ${{ secrets.GLOBAL_TOKEN }}
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#        if: env.WORKFLOW_CONCLUSION == 'failure'
